USE master
GO
CREATE DATABASE QuanLyBanThuoc
GO
USE QuanLyBanThuoc
GO

CREATE TABLE LOAITHUOC 
(
	MaLoai VARCHAR (10) PRIMARY KEY, 
	TenLoai NVARCHAR (30) NOT NULL
)
GO

CREATE TABLE THUOC
(
	MaThuoc VARCHAR (10) PRIMARY KEY,
	TenThuoc NVARCHAR (100) NOT NULL,
	DonGia FLOAT (10),
	DVT NVARCHAR (30),
	MaLoai VARCHAR (10) FOREIGN KEY REFERENCES LOAITHUOC (MaLoai)
)
GO

CREATE TABLE NHANVIEN
(
	MaNV VARCHAR (10) PRIMARY KEY,
	TenNV NVARCHAR (35) NOT NULL,
	DiaChi NVARCHAR (100),
	DienThoai VARCHAR (12) UNIQUE
)
GO

CREATE TABLE KHACHHANG
(
	MaKH VARCHAR (10) PRIMARY KEY,
	TenKH NVARCHAR (35) NOT NULL,
	DiaChi NVARCHAR (100),
	DienThoai VARCHAR (12) UNIQUE
)
GO

CREATE TABLE HOADON
(
	SoHD VARCHAR (15) PRIMARY KEY,
	NgayMua DATETIME,
	TongTien FLOAT,
	MaKH VARCHAR (10) FOREIGN KEY REFERENCES KHACHHANG (MaKH),
	MaNV VARCHAR (10) FOREIGN KEY REFERENCES NHANVIEN (MaNV),
)
GO

CREATE TABLE CHITIETHOADON
(
	MaThuoc VARCHAR (10) REFERENCES THUOC (MaThuoc),
	SoHD VARCHAR (15) REFERENCES HOADON (SoHD),
	SoLuong INT
)
GO
